# Schema for the configuration files of the creneaumylittlepressing module.
creneaumylittlepressing.settings:
  type: config_object
  label: 'creneaumylittlepressing settings'
  mapping:
    example:
      type: string
      label: 'Example'
